### ISSUE TITLE
It would be cool to support password or 2fa for escalation

### ISSUE THREAD

**Issue by ChrisMacNaughton** [markets/sudo_rails#13]

**Comment by ChrisMacNaughton** [comment]
It's not [_super_ hard to implement](https://github.com/CentauriSolutions/EyeDP/pull/321) but it does mean deviating from this gem's handling of confirm almost completely :-P

**Comment by markets** [comment]
Hey @ChrisMacNaughton 👋🏼 sorry the late reply 🙏🏼 

As you said, this is probably out of the scope of this gem! But since you can use a custom "Confirmation strategy" (https://github.com/markets/sudo_rails#confirmation-strategy), you have some flexibility to handle it at your own.

**Comment by markets** [comment]
Hey @ChrisMacNaughton 👋🏼 

I just shipped (`v0.9.0`) with something that brings some extra flexibility and will probably allow some other workflows to be implemented. With the new [Callbacks](https://github.com/markets/sudo_rails#callbacks), you can now add custom callable objects at some points of the lifecycle.
